-- Notiva initial PostgreSQL schema.
-- Existing databases are baselined at version 1 before this migration is enabled.
-- Fresh databases require pgvector because semantic-search embeddings use vector(512).

CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    avatar_public_id VARCHAR(255),
    avatar_url VARCHAR(500),
    display_name VARCHAR(100) NOT NULL,
    email VARCHAR(255) NOT NULL,
    email_verified BOOLEAN NOT NULL,
    enabled BOOLEAN NOT NULL,
    google_id VARCHAR(255),
    password VARCHAR(255),
    plan VARCHAR(20) NOT NULL,
    role VARCHAR(20) NOT NULL,
    CONSTRAINT uk_users_email UNIQUE (email),
    CONSTRAINT uk_users_google_id UNIQUE (google_id),
    CONSTRAINT users_plan_check CHECK (plan IN ('NORMAL', 'PREMIUM')),
    CONSTRAINT users_role_check CHECK (role IN ('USER', 'ADMIN'))
);

CREATE TABLE categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    name VARCHAR(100) NOT NULL,
    user_id BIGINT NOT NULL,
    CONSTRAINT fk_categories_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT uk_categories_user_name UNIQUE (user_id, name)
);

CREATE TABLE notes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    background_color VARCHAR(20) NOT NULL,
    content_json TEXT NOT NULL,
    deleted_at TIMESTAMP(6),
    favorite BOOLEAN NOT NULL,
    pinned BOOLEAN NOT NULL,
    plain_text TEXT NOT NULL,
    title VARCHAR(255) NOT NULL,
    category_id BIGINT,
    user_id BIGINT NOT NULL,
    CONSTRAINT fk_notes_category FOREIGN KEY (category_id) REFERENCES categories (id),
    CONSTRAINT fk_notes_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT notes_background_color_check CHECK (
        background_color IN ('DEFAULT', 'YELLOW', 'GREEN', 'BLUE', 'PINK', 'PURPLE', 'GRAY')
    )
);

CREATE TABLE note_versions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6) NOT NULL,
    content_json TEXT NOT NULL,
    plain_text TEXT NOT NULL,
    title VARCHAR(255) NOT NULL,
    note_id BIGINT NOT NULL,
    CONSTRAINT fk_note_versions_note FOREIGN KEY (note_id) REFERENCES notes (id)
);

CREATE TABLE auth_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6) NOT NULL,
    expires_at TIMESTAMP(6) NOT NULL,
    token VARCHAR(255) NOT NULL,
    type VARCHAR(30) NOT NULL,
    used BOOLEAN NOT NULL,
    user_id BIGINT NOT NULL,
    CONSTRAINT fk_auth_tokens_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT uk_auth_tokens_token UNIQUE (token),
    CONSTRAINT auth_tokens_type_check CHECK (
        type IN ('EMAIL_VERIFICATION', 'PASSWORD_RESET_OTP', 'REFRESH_TOKEN')
    )
);

CREATE TABLE ai_conversations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    title VARCHAR(100) NOT NULL,
    type VARCHAR(30) NOT NULL,
    note_id BIGINT,
    user_id BIGINT NOT NULL,
    CONSTRAINT fk_ai_conversations_note FOREIGN KEY (note_id) REFERENCES notes (id),
    CONSTRAINT fk_ai_conversations_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT ai_conversations_type_check CHECK (type IN ('NOTE_CHAT', 'ALL_NOTES_CHAT'))
);

CREATE TABLE ai_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6) NOT NULL,
    content TEXT NOT NULL,
    role VARCHAR(20) NOT NULL,
    conversation_id BIGINT NOT NULL,
    CONSTRAINT fk_ai_messages_conversation FOREIGN KEY (conversation_id)
        REFERENCES ai_conversations (id),
    CONSTRAINT ai_messages_role_check CHECK (role IN ('USER', 'ASSISTANT'))
);

CREATE TABLE ai_usage (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    request_count INTEGER NOT NULL,
    usage_date DATE NOT NULL,
    user_id BIGINT NOT NULL,
    CONSTRAINT fk_ai_usage_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT uk_ai_usage_user_date UNIQUE (user_id, usage_date)
);

CREATE TABLE note_chunks (
    id BIGSERIAL PRIMARY KEY,
    content TEXT NOT NULL,
    chunk_index INTEGER NOT NULL,
    embedding VECTOR(512) NOT NULL,
    note_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_note_chunks_note FOREIGN KEY (note_id) REFERENCES notes (id) ON DELETE CASCADE,
    CONSTRAINT fk_note_chunks_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT uk_note_chunks_note_index UNIQUE (note_id, chunk_index)
);

CREATE INDEX idx_categories_user_id ON categories (user_id);
CREATE INDEX idx_notes_user_id ON notes (user_id);
CREATE INDEX idx_notes_category_id ON notes (category_id);
CREATE INDEX idx_notes_deleted_at ON notes (deleted_at);
CREATE INDEX idx_notes_user_deleted_at ON notes (user_id, deleted_at);
CREATE INDEX idx_note_versions_note_id ON note_versions (note_id);
CREATE INDEX idx_note_versions_note_created_at ON note_versions (note_id, created_at);
CREATE INDEX idx_auth_tokens_user_type ON auth_tokens (user_id, type);
CREATE INDEX idx_auth_tokens_expires_at ON auth_tokens (expires_at);
CREATE INDEX idx_ai_conversations_user_id ON ai_conversations (user_id);
CREATE INDEX idx_ai_conversations_note_id ON ai_conversations (note_id);
CREATE INDEX idx_ai_conversations_user_updated_at ON ai_conversations (user_id, updated_at);
CREATE INDEX idx_ai_messages_conversation_id ON ai_messages (conversation_id);
CREATE INDEX idx_ai_messages_conversation_created_at ON ai_messages (conversation_id, created_at);
CREATE INDEX idx_ai_usage_user_id ON ai_usage (user_id);
CREATE INDEX idx_note_chunks_note_id ON note_chunks (note_id);
CREATE INDEX idx_note_chunks_user_id ON note_chunks (user_id);
